name: Performance Benchmarks

on:
  push:
    branches: [ main, develop, TheDefaultBranch ]
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Godot
      uses: chickensoft-games/setup-godot@v2
      with:
        version: '4.4.1'
        include-templates: true
        
    - name: Cache Godot import
      uses: actions/cache@v4
      with:
        path: .godot/
        key: godot-perf-${{ hashFiles('**/*.gd', '**/*.tscn', '**/*.tres') }}
        
    - name: Import project
      run: godot --headless --import --quit-after 10
      
    - name: Run performance benchmarks
      run: godot --headless --script scripts/benchmarks/BenchmarkRunner.gd --quit-after 120
      
    - name: Download previous benchmarks
      uses: actions/download-artifact@v4
      with:
        name: benchmark-history
        path: benchmark-history/
      continue-on-error: true
      
    - name: Compare performance
      run: |
        if [ -f "benchmark-history/latest-benchmarks.json" ]; then
          godot --headless --script scripts/benchmarks/PerformanceComparer.gd -- benchmark-history/latest-benchmarks.json benchmark-results.json
        fi
      
    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-history
        path: |
          benchmark-results.json
          performance-report.html
          benchmark-charts/
        retention-days: 30
        
    - name: Comment PR with performance results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          if (fs.existsSync('performance-summary.md')) {
            const summary = fs.readFileSync('performance-summary.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });
          }