name: Build Verification

on:
  push:
    branches: [ main, develop, TheDefaultBranch ]
  pull_request:
    branches: [ main, develop, TheDefaultBranch ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        godot-version: ['4.4.1']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Godot
      uses: chickensoft-games/setup-godot@v2
      with:
        version: ${{ matrix.godot-version }}
        include-templates: true
        
    - name: Cache Godot import
      uses: actions/cache@v4
      with:
        path: .godot/
        key: godot-build-${{ matrix.os }}-${{ matrix.godot-version }}-${{ hashFiles('**/*.gd', '**/*.tscn', '**/*.tres') }}
        
    - name: Import and validate project
      run: godot --headless --validate-only --quit-after 30
      
    - name: Check for script errors
      run: godot --headless --check-only --quit-after 30
      
    - name: Generate export templates (if needed)
      if: matrix.os == 'ubuntu-latest'
      run: |
        mkdir -p export-templates
        echo "Export template generation placeholder" > export-templates/README.md
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: build-artifacts-${{ matrix.os }}
        path: |
          .godot/
          export-templates/
        retention-days: 3